name: Build C Project on Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        choco install make
        choco install mingw

    - name: Build
      run: make
